### PR TITLE
Update the README with version badge and number of downloads

### PR DESCRIPTION
**Pull request by pedramp**
PR #12

### CODE REVIEW

**Review by ameerthehacker — APPROVED** [review]

**Review by ameerthehacker — CHANGES_REQUESTED** [review]
The downloads badge is breaking can you please check and also place the badges centered above the screenshot

**Review by ameerthehacker — CHANGES_REQUESTED** [review]
Everything is good yet can you please move the badges above the image as it might look good

**Comment by pedramp** [comment]
@ameerthehacker updated

**Review by ameerthehacker — APPROVED** [review]

**Comment by ameerthehacker** [comment]
cool Thanks for the contribution

**Pull request merged**
